name: Build & Deploy (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: |
          echo "TAG=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t parastoneglobal/masdar-web:${{ steps.vars.outputs.TAG }} .

      - name: Push Docker Image
        run: |
          docker push parastoneglobal/masdar-web:${{ steps.vars.outputs.TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/masdar-web-docker

            docker compose pull

            if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
              docker compose up -d staging
            else
              docker compose up -d production
            fi